namespace BotExtended.Factions
{
    public enum BotFaction
    {
        None = 0,
        Assassin,
        Agent,
        Bandido,
        Biker,
        Clown,
        Cowboy,
        Engineer,
        Gangster,
        Survivor,
        MetroCop,
        Police,
        PoliceSWAT,
        Sniper,
        Soldier,
        Spacer,
        Stripper,
        Thug,
        Punk,
        Zombie,
        ZombieMutated,

        Boss_Demolitionist = Constants.BOSS_FACTION_START_INDEX,
        Boss_Balista,
        Boss_Boffin,
        Boss_Cindy,
        Boss_Funnyman,
        Boss_Jo,
        Boss_Hacker,
        Boss_Incinerator,
        Boss_Kingpin,
        Boss_MadScientist,
        Boss_Meatgrinder,
        Boss_Mecha,
        Boss_MetroCop,
        Boss_MirrorMan,
        Boss_Ninja,
        Boss_Santa,
        Boss_Sheriff,
        Boss_Teddybear,
        Boss_Zombie,
    }
}
