using SFDGameScriptInterface;
using System.Collections.Generic;

namespace ChallengePlus
{
    public enum ProfileType
    {
        Ninja,
        Zombie
    }

    public static class ProfileDatabase
    {
        private static IProfileClothingItem CloneClothingItem(IProfileClothingItem clothingItem)
        {
            if (clothingItem == null) return null;
            return new IProfileClothingItem(clothingItem.Name, clothingItem.Color1, clothingItem.Color2, clothingItem.Color3);
        }

        public static IProfile Clone(IProfile profile)
        {
            if (profile == null) return null;
            return new IProfile
            {
                Name = profile.Name,
                Gender = profile.Gender,
                Accessory = CloneClothingItem(profile.Accessory),
                ChestOver = CloneClothingItem(profile.ChestOver),
                ChestUnder = CloneClothingItem(profile.ChestUnder),
                Head = CloneClothingItem(profile.Head),
                Waist = CloneClothingItem(profile.Waist),
                Hands = CloneClothingItem(profile.Hands),
                Legs = CloneClothingItem(profile.Legs),
                Skin = CloneClothingItem(profile.Skin),
                Feet = CloneClothingItem(profile.Feet),
            };
        }

        public static IProfile Get(ProfileType profile)
        {
            var profiles = new List<IProfile>();

            // UPDATE: SFD.Weapons.WeaponDatabase 1.3.4
            switch (profile)
            {
                case ProfileType.Ninja:
                {
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiTmluamEiLCJnZW5kZXIiOjAsInNraW4iOnsiaWQiOiJOb3JtYWwiLCJjb2xvcnMiOlsiU2tpbjMiLCJDbG90aGluZ0xpZ2h0R3JheSIsbnVsbF19LCJoZWFkIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiU3dlYXRlckJsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0dyYXkiLG51bGwsbnVsbF19LCJoYW5kcyI6eyJpZCI6IkZpbmdlcmxlc3NHbG92ZXNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLG51bGwsbnVsbF19LCJ3YWlzdCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJsZWdzIjp7ImlkIjoiUGFudHNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6IkJhbGFjbGF2YSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Ninja", Gender = Gender.Male, Skin = new IProfileClothingItem("Normal", "Skin3", "ClothingLightGray"), ChestUnder = new IProfileClothingItem("SweaterBlack", "ClothingDarkGray"), Hands = new IProfileClothingItem("FingerlessGlovesBlack", "ClothingGray"), Legs = new IProfileClothingItem("PantsBlack", "ClothingDarkGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkGray"), Accesory = new IProfileClothingItem("Balaclava", "ClothingDarkGray"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiTmluamEiLCJnZW5kZXIiOjEsInNraW4iOnsiaWQiOiJOb3JtYWxfZmVtIiwiY29sb3JzIjpbIlNraW4zIiwiQ2xvdGhpbmdMaWdodEdyYXkiLG51bGxdfSwiaGVhZCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlN3ZWF0ZXJCbGFja19mZW0iLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiRmluZ2VybGVzc0dsb3Zlc0JsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nR3JheSIsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50c0JsYWNrX2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6IkJhbGFjbGF2YSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Ninja", Gender = Gender.Female, Skin = new IProfileClothingItem("Normal_fem", "Skin3", "ClothingLightGray"), ChestUnder = new IProfileClothingItem("SweaterBlack_fem", "ClothingDarkGray"), Hands = new IProfileClothingItem("FingerlessGlovesBlack", "ClothingGray"), Legs = new IProfileClothingItem("PantsBlack_fem", "ClothingDarkGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkGray"), Accesory = new IProfileClothingItem("Balaclava", "ClothingDarkGray"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiTmluamEiLCJnZW5kZXIiOjEsInNraW4iOnsiaWQiOiJOb3JtYWxfZmVtIiwiY29sb3JzIjpbIlNraW4zIiwiQ2xvdGhpbmdMaWdodEdyYXkiLG51bGxdfSwiaGVhZCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlN3ZWF0ZXJCbGFja19mZW0iLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiRmluZ2VybGVzc0dsb3Zlc0JsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nR3JheSIsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50c0JsYWNrX2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ik1hc2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrUmVkIixudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Ninja", Gender = Gender.Female, Skin = new IProfileClothingItem("Normal_fem", "Skin3", "ClothingLightGray"), ChestUnder = new IProfileClothingItem("SweaterBlack_fem", "ClothingDarkGray"), Hands = new IProfileClothingItem("FingerlessGlovesBlack", "ClothingGray"), Legs = new IProfileClothingItem("PantsBlack_fem", "ClothingDarkGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkGray"), Accesory = new IProfileClothingItem("Mask", "ClothingDarkRed"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiTmluamEiLCJnZW5kZXIiOjAsInNraW4iOnsiaWQiOiJOb3JtYWwiLCJjb2xvcnMiOlsiU2tpbjMiLCJDbG90aGluZ0xpZ2h0R3JheSIsbnVsbF19LCJoZWFkIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiU3dlYXRlckJsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0dyYXkiLG51bGwsbnVsbF19LCJoYW5kcyI6eyJpZCI6IkZpbmdlcmxlc3NHbG92ZXNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLG51bGwsbnVsbF19LCJ3YWlzdCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJsZWdzIjp7ImlkIjoiUGFudHNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ik1hc2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrUmVkIixudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Ninja", Gender = Gender.Male, Skin = new IProfileClothingItem("Normal", "Skin3", "ClothingLightGray"), ChestUnder = new IProfileClothingItem("SweaterBlack", "ClothingDarkGray"), Hands = new IProfileClothingItem("FingerlessGlovesBlack", "ClothingGray"), Legs = new IProfileClothingItem("PantsBlack", "ClothingDarkGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkGray"), Accesory = new IProfileClothingItem("Mask", "ClothingDarkRed"), });
                    break;
                }
                case ProfileType.Zombie:
                {
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIiwiZ2VuZGVyIjoxLCJza2luIjp7ImlkIjoiWm9tYmllX2ZlbSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImhlYWQiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RPdmVyIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImNoZXN0VW5kZXIiOnsiaWQiOiJUb3JuU2hpcnRfZmVtIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0JsdWUiLG51bGwsbnVsbF19LCJoYW5kcyI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJ3YWlzdCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJsZWdzIjp7ImlkIjoiVG9yblBhbnRzX2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie", Gender = Gender.Female, Skin = new IProfileClothingItem("Zombie_fem", ""), ChestUnder = new IProfileClothingItem("TornShirt_fem", "ClothingDarkBlue"), Legs = new IProfileClothingItem("TornPants_fem", "ClothingDarkBlue"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlRvcm5TaGlydCIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiaGFuZHMiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwid2Fpc3QiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwibGVncyI6eyJpZCI6IlRvcm5QYW50cyIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), ChestUnder = new IProfileClothingItem("TornShirt", "ClothingDarkBlue"), Legs = new IProfileClothingItem("TornPants", "ClothingDarkBlue"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIEFnZW50IiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJTdWl0SmFja2V0QmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbCxudWxsXX0sImNoZXN0VW5kZXIiOnsiaWQiOiJTaGlydFdpdGhUaWUiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IiwiQ2xvdGhpbmdEYXJrR3JheSIsbnVsbF19LCJoYW5kcyI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJ3YWlzdCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJsZWdzIjp7ImlkIjoiUGFudHNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQnJvd24iLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJTdW5HbGFzc2VzIiwiY29sb3JzIjpbbnVsbCwiQ2xvdGhpbmdMaWdodEdyYXkiLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Agent", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), ChestOver = new IProfileClothingItem("SuitJacketBlack", "ClothingDarkGray"), ChestUnder = new IProfileClothingItem("ShirtWithTie", "ClothingGray", "ClothingDarkGray"), Legs = new IProfileClothingItem("PantsBlack", "ClothingDarkGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkBrown"), Accesory = new IProfileClothingItem("SunGlasses", "", "ClothingLightGray", ""), });


                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIEdhbmdzdGVyIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IlN0eWxpc2hIYXQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IiwiQ2xvdGhpbmdQaW5rIixudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6IkJsYXplcldpdGhTaGlydCIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLCJDbG90aGluZ0xpZ2h0Qmx1ZSIsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJUb3JuUGFudHMiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiYWNjZXNzb3J5Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX19
                    profiles.Add(new IProfile() { Name = "Zombie Gangster", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("StylishHat", "ClothingGray", "ClothingPink"), ChestOver = new IProfileClothingItem("BlazerWithShirt", "ClothingGray", "ClothingLightBlue"), Legs = new IProfileClothingItem("TornPants", "ClothingGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingGray"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIEdhbmdzdGVyIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IkZsYXRjYXAiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiY2hlc3RPdmVyIjp7ImlkIjoiU3VzcGVuZGVycyIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLCJDbG90aGluZ0RhcmtZZWxsb3ciLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlNoaXJ0V2l0aFRpZSIsImNvbG9ycyI6WyJDbG90aGluZ1BpbmsiLCJDbG90aGluZ0RhcmtQaW5rIixudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJUb3JuUGFudHMiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiYWNjZXNzb3J5Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX19
                    profiles.Add(new IProfile() { Name = "Zombie Gangster", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("Flatcap", "ClothingGray"), ChestOver = new IProfileClothingItem("Suspenders", "ClothingGray", "ClothingDarkYellow"), ChestUnder = new IProfileClothingItem("ShirtWithTie", "ClothingPink", "ClothingDarkPink"), Legs = new IProfileClothingItem("TornPants", "ClothingGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingGray"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIEdhbmdzdGVyIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IlN0eWxpc2hIYXQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IiwiQ2xvdGhpbmdEYXJrWWVsbG93IixudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6IlN1aXRKYWNrZXQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJoYW5kcyI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJ3YWlzdCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJsZWdzIjp7ImlkIjoiVG9yblBhbnRzIiwiY29sb3JzIjpbIkNsb3RoaW5nR3JheSIsbnVsbCxudWxsXX0sImZlZXQiOnsiaWQiOiJTaG9lc0JsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nR3JheSIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19fQ--
                    profiles.Add(new IProfile() { Name = "Zombie Gangster", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("StylishHat", "ClothingGray", "ClothingDarkYellow"), ChestOver = new IProfileClothingItem("SuitJacket", "ClothingGray"), Legs = new IProfileClothingItem("TornPants", "ClothingGray"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingGray"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIEdhbmdzdGVyIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IkZlZG9yYSIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLCJDbG90aGluZ0RhcmtQaW5rIixudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6IlN1aXRKYWNrZXQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IixudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlNoaXJ0V2l0aFRpZSIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLCJDbG90aGluZ0RhcmtQaW5rIixudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50cyIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiQm9vdHNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Gangster", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("Fedora", "ClothingGray", "ClothingDarkPink"), ChestOver = new IProfileClothingItem("SuitJacket", "ClothingGray"), ChestUnder = new IProfileClothingItem("ShirtWithTie", "ClothingGray", "ClothingDarkPink"), Legs = new IProfileClothingItem("Pants", "ClothingGray"), Feet = new IProfileClothingItem("BootsBlack", "ClothingGray"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIEdhbmdzdGVyIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJCbGF6ZXJXaXRoU2hpcnQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdHcmF5IiwiQ2xvdGhpbmdEYXJrUGluayIsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50cyIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiQm9vdHNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0dyYXkiLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Gangster", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), ChestOver = new IProfileClothingItem("BlazerWithShirt", "ClothingGray", "ClothingDarkPink"), Legs = new IProfileClothingItem("Pants", "ClothingGray"), Feet = new IProfileClothingItem("BootsBlack", "ClothingGray"), });

                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIE5pbmphIiwiZ2VuZGVyIjoxLCJza2luIjp7ImlkIjoiWm9tYmllX2ZlbSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImhlYWQiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RPdmVyIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImNoZXN0VW5kZXIiOnsiaWQiOiJUcmFpbmluZ1NoaXJ0X2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiaGFuZHMiOnsiaWQiOiJGaW5nZXJsZXNzR2xvdmVzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQmx1ZSIsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiU2FzaF9mZW0iLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrUmVkIixudWxsLG51bGxdfSwibGVncyI6eyJpZCI6IlBhbnRzX2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IlNob2VzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQmx1ZSIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ik1hc2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrUmVkIixudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Ninja", Gender = Gender.Female, Skin = new IProfileClothingItem("Zombie_fem", ""), ChestUnder = new IProfileClothingItem("TrainingShirt_fem", "ClothingDarkBlue"), Hands = new IProfileClothingItem("FingerlessGlovesBlack", "ClothingDarkBlue"), Waist = new IProfileClothingItem("Sash_fem", "ClothingDarkRed"), Legs = new IProfileClothingItem("Pants_fem", "ClothingDarkBlue"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkBlue"), Accesory = new IProfileClothingItem("Mask", "ClothingDarkRed"), });

                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFBvbGljZSIsImdlbmRlciI6MSwic2tpbiI6eyJpZCI6IlpvbWJpZV9mZW0iLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJoZWFkIjp7ImlkIjoiUG9saWNlSGF0IiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0JsdWUiLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlBvbGljZVNoaXJ0X2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiaGFuZHMiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwid2Fpc3QiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwibGVncyI6eyJpZCI6IlBhbnRzQmxhY2tfZmVtIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0JsdWUiLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiU2hvZXMiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQnJvd24iLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Police", Gender = Gender.Female, Skin = new IProfileClothingItem("Zombie_fem", ""), Head = new IProfileClothingItem("PoliceHat", "ClothingDarkBlue"), ChestUnder = new IProfileClothingItem("PoliceShirt_fem", "ClothingDarkBlue"), Legs = new IProfileClothingItem("PantsBlack_fem", "ClothingDarkBlue"), Feet = new IProfileClothingItem("Shoes", "ClothingDarkBrown"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFBvbGljZSIsImdlbmRlciI6MCwic2tpbiI6eyJpZCI6IlpvbWJpZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImhlYWQiOnsiaWQiOiJQb2xpY2VIYXQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQmx1ZSIsbnVsbCxudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiUG9saWNlU2hpcnQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQmx1ZSIsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50c0JsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0JsdWUiLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiU2hvZXMiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQnJvd24iLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Police", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("PoliceHat", "ClothingDarkBlue"), ChestUnder = new IProfileClothingItem("PoliceShirt", "ClothingDarkBlue"), Legs = new IProfileClothingItem("PantsBlack", "ClothingDarkBlue"), Feet = new IProfileClothingItem("Shoes", "ClothingDarkBrown"), });

                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFBydXNzaWFuIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IlNwaWtlZEhlbG1ldCIsImNvbG9ycyI6WyJDbG90aGluZ0N5YW4iLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IkxlYXRoZXJKYWNrZXRCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0N5YW4iLCJDbG90aGluZ0xpZ2h0R3JheSIsbnVsbF19LCJoYW5kcyI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJ3YWlzdCI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJsZWdzIjp7ImlkIjoiVG9yblBhbnRzIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0N5YW4iLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiQm9vdHNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtDeWFuIixudWxsLG51bGxdfSwiYWNjZXNzb3J5Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX19
                    profiles.Add(new IProfile() { Name = "Zombie Prussian", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("SpikedHelmet", "ClothingCyan"), ChestUnder = new IProfileClothingItem("LeatherJacketBlack", "ClothingCyan", "ClothingLightGray"), Legs = new IProfileClothingItem("TornPants", "ClothingDarkCyan"), Feet = new IProfileClothingItem("BootsBlack", "ClothingDarkCyan"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFBydXNzaWFuIiwiZ2VuZGVyIjowLCJza2luIjp7ImlkIjoiWm9tYmllIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IlNwaWtlZEhlbG1ldCIsImNvbG9ycyI6WyJDbG90aGluZ0N5YW4iLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlRvcm5TaGlydCIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtDeWFuIixudWxsLG51bGxdfSwiaGFuZHMiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwid2Fpc3QiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwibGVncyI6eyJpZCI6IlRvcm5QYW50cyIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtDeWFuIixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IkJvb3RzQmxhY2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQ3lhbiIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ikdhc01hc2siLCJjb2xvcnMiOlsiQ2xvdGhpbmdDeWFuIiwiQ2xvdGhpbmdMaWdodEdyZWVuIixudWxsXX19
                    profiles.Add(new IProfile() { Name = "Zombie Prussian", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("SpikedHelmet", "ClothingCyan"), ChestUnder = new IProfileClothingItem("TornShirt", "ClothingDarkCyan"), Legs = new IProfileClothingItem("TornPants", "ClothingDarkCyan"), Feet = new IProfileClothingItem("BootsBlack", "ClothingDarkCyan"), Accesory = new IProfileClothingItem("GasMask", "ClothingCyan", "ClothingLightGreen"), });

                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFNvbGRpZXIiLCJnZW5kZXIiOjEsInNraW4iOnsiaWQiOiJab21iaWVfZmVtIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IkhlbG1ldCIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtZZWxsb3ciLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlRvcm5TaGlydF9mZW0iLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrWWVsbG93IixudWxsLG51bGxdfSwiaGFuZHMiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwid2Fpc3QiOnsiaWQiOiJBbW1vQmVsdFdhaXN0X2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0Jyb3duIixudWxsLG51bGxdfSwibGVncyI6eyJpZCI6IkNhbW9QYW50c19mZW0iLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrWWVsbG93IiwiQ2xvdGhpbmdEYXJrWWVsbG93IixudWxsXX0sImZlZXQiOnsiaWQiOiJCb290cyIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtSZWQiLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Soldier", Gender = Gender.Female, Skin = new IProfileClothingItem("Zombie_fem", ""), Head = new IProfileClothingItem("Helmet", "ClothingDarkYellow"), ChestUnder = new IProfileClothingItem("TornShirt_fem", "ClothingDarkYellow"), Waist = new IProfileClothingItem("AmmoBeltWaist_fem", "ClothingBrown"), Legs = new IProfileClothingItem("CamoPants_fem", "ClothingDarkYellow", "ClothingDarkYellow"), Feet = new IProfileClothingItem("Boots", "ClothingDarkRed"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFNvbGRpZXIiLCJnZW5kZXIiOjAsInNraW4iOnsiaWQiOiJab21iaWUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJoZWFkIjp7ImlkIjoiSGVsbWV0IiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya1llbGxvdyIsbnVsbCxudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiVG9yblNoaXJ0IiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya1llbGxvdyIsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiQW1tb0JlbHRXYWlzdCIsImNvbG9ycyI6WyJDbG90aGluZ0Jyb3duIixudWxsLG51bGxdfSwibGVncyI6eyJpZCI6IkNhbW9QYW50cyIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtZZWxsb3ciLCJDbG90aGluZ0RhcmtZZWxsb3ciLG51bGxdfSwiZmVldCI6eyJpZCI6IkJvb3RzIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya1JlZCIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19fQ--
                    profiles.Add(new IProfile() { Name = "Zombie Soldier", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("Helmet", "ClothingDarkYellow"), ChestUnder = new IProfileClothingItem("TornShirt", "ClothingDarkYellow"), Waist = new IProfileClothingItem("AmmoBeltWaist", "ClothingBrown"), Legs = new IProfileClothingItem("CamoPants", "ClothingDarkYellow", "ClothingDarkYellow"), Feet = new IProfileClothingItem("Boots", "ClothingDarkRed"), });

                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFRodWciLCJnZW5kZXIiOjEsInNraW4iOnsiaWQiOiJab21iaWVfZmVtIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwiaGVhZCI6eyJpZCI6IkhlYWRiYW5kIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya1JlZCIsbnVsbCxudWxsXX0sImNoZXN0T3ZlciI6eyJpZCI6IlZlc3RfZmVtIiwiY29sb3JzIjpbIkNsb3RoaW5nTGlnaHRCbHVlIiwiQ2xvdGhpbmdMaWdodEJsdWUiLG51bGxdfSwiY2hlc3RVbmRlciI6eyJpZCI6IlNsZWV2ZWxlc3NTaGlydF9mZW0iLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQmx1ZSIsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50c0JsYWNrX2ZlbSIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCbHVlIixudWxsLG51bGxdfSwiZmVldCI6eyJpZCI6IkJvb3RzIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0Jyb3duIixudWxsLG51bGxdfSwiYWNjZXNzb3J5Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX19
                    profiles.Add(new IProfile() { Name = "Zombie Thug", Gender = Gender.Female, Skin = new IProfileClothingItem("Zombie_fem", ""), Head = new IProfileClothingItem("Headband", "ClothingDarkRed"), ChestOver = new IProfileClothingItem("Vest_fem", "ClothingLightBlue", "ClothingLightBlue"), ChestUnder = new IProfileClothingItem("SleevelessShirt_fem", "ClothingDarkBlue"), Legs = new IProfileClothingItem("PantsBlack_fem", "ClothingDarkBlue"), Feet = new IProfileClothingItem("Boots", "ClothingDarkBrown"), });
                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFRodWciLCJnZW5kZXIiOjAsInNraW4iOnsiaWQiOiJab21iaWUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19LCJoZWFkIjp7ImlkIjoiSGVhZGJhbmQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrUmVkIixudWxsLG51bGxdfSwiY2hlc3RPdmVyIjp7ImlkIjoiVmVzdCIsImNvbG9ycyI6WyJDbG90aGluZ0xpZ2h0Qmx1ZSIsIkNsb3RoaW5nTGlnaHRCbHVlIixudWxsXX0sImNoZXN0VW5kZXIiOnsiaWQiOiJTbGVldmVsZXNzU2hpcnQiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQmx1ZSIsbnVsbCxudWxsXX0sImhhbmRzIjp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sIndhaXN0Ijp7ImlkIjoiTm9uZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJQYW50c0JsYWNrIiwiY29sb3JzIjpbIkNsb3RoaW5nRGFya0JsdWUiLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiQm9vdHMiLCJjb2xvcnMiOlsiQ2xvdGhpbmdEYXJrQnJvd24iLG51bGwsbnVsbF19LCJhY2Nlc3NvcnkiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfX0-
                    profiles.Add(new IProfile() { Name = "Zombie Thug", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("Headband", "ClothingDarkRed"), ChestOver = new IProfileClothingItem("Vest", "ClothingLightBlue", "ClothingLightBlue"), ChestUnder = new IProfileClothingItem("SleevelessShirt", "ClothingDarkBlue"), Legs = new IProfileClothingItem("PantsBlack", "ClothingDarkBlue"), Feet = new IProfileClothingItem("Boots", "ClothingDarkBrown"), });

                    // https://profile-editor.vercel.app?tab=profile&p=eyJuYW1lIjoiWm9tYmllIFdvcmtlciIsImdlbmRlciI6MCwic2tpbiI6eyJpZCI6IlpvbWJpZSIsImNvbG9ycyI6W251bGwsbnVsbCxudWxsXX0sImhlYWQiOnsiaWQiOiJDYXAiLCJjb2xvcnMiOlsiQ2xvdGhpbmdZZWxsb3ciLG51bGwsbnVsbF19LCJjaGVzdE92ZXIiOnsiaWQiOiJTdXNwZW5kZXJzIiwiY29sb3JzIjpbIkNsb3RoaW5nT3JhbmdlIiwiQ2xvdGhpbmdMaWdodE9yYW5nZSIsbnVsbF19LCJjaGVzdFVuZGVyIjp7ImlkIjoiVG9yblNoaXJ0IiwiY29sb3JzIjpbIkNsb3RoaW5nT3JhbmdlIixudWxsLG51bGxdfSwiaGFuZHMiOnsiaWQiOiJOb25lIiwiY29sb3JzIjpbbnVsbCxudWxsLG51bGxdfSwid2Fpc3QiOnsiaWQiOiJTYXRjaGVsQmVsdCIsImNvbG9ycyI6WyJDbG90aGluZ09yYW5nZSIsbnVsbCxudWxsXX0sImxlZ3MiOnsiaWQiOiJUb3JuUGFudHMiLCJjb2xvcnMiOlsiQ2xvdGhpbmdPcmFuZ2UiLG51bGwsbnVsbF19LCJmZWV0Ijp7ImlkIjoiU2hvZXNCbGFjayIsImNvbG9ycyI6WyJDbG90aGluZ0RhcmtCcm93biIsbnVsbCxudWxsXX0sImFjY2Vzc29yeSI6eyJpZCI6Ik5vbmUiLCJjb2xvcnMiOltudWxsLG51bGwsbnVsbF19fQ--
                    profiles.Add(new IProfile() { Name = "Zombie Worker", Gender = Gender.Male, Skin = new IProfileClothingItem("Zombie", ""), Head = new IProfileClothingItem("Cap", "ClothingYellow"), ChestOver = new IProfileClothingItem("Suspenders", "ClothingOrange", "ClothingLightOrange"), ChestUnder = new IProfileClothingItem("TornShirt", "ClothingOrange"), Waist = new IProfileClothingItem("SatchelBelt", "ClothingOrange"), Legs = new IProfileClothingItem("TornPants", "ClothingOrange"), Feet = new IProfileClothingItem("ShoesBlack", "ClothingDarkBrown"), });
                    break;
                }
            }

            return Clone(RandomHelper.GetItem(profiles));
        }
    }
}
