namespace BotExtended.Projectiles
{
    public enum RangedWeaponPowerup
    {
        None,
        Blackhole,
        Blast,
        DoubleTrouble,
        Fatigue,
        Helium,
        Hunting,
        Homing,
        Gauss,
        Grapeshot,
        Gravity,
        GravityDE,
        Minigun,
        Lightning,
        Poison,
        Present,
        Riding,
        Smoke,
        Stun,
        Spinner,
        StickyBomb,
        SuicideDove,
        SuicideFighter,
        Taser,
        Tearing,
        Welding,
    }
}
